GET http://localhost:5000/ HTTP/1.1

###

POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
     "name":"Erign T",
     "email":"ergin@mail.com",
     "password":"1"

}

###

POST http://localhost:5000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email":"ergin@mail.com",
    "password":"1"
}

###